### PR TITLE
CI: migrate from travis to GH actions

### LINKED ISSUE #42: CI broken?
Whatever the travis CI workflow was intended to do, it'd probably be best to migrate it to GitHub Actions:

https://github.com/mne-tools/fiff-constants/blob/6d9ca9ce7fb44c63d429c2986a953500743dfb22/.travis.yml#L1-L6

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #42 

not sure if this will do the job. cc @larsoner

### CODE REVIEW

**Comment by larsoner** [comment]
Thanks @sappelhoff !

**Comment by larsoner** [comment]
Looks like it just needed to be merged to run the first time, and it was green:

https://github.com/mne-tools/fiff-constants/runs/8247789021?check_suite_focus=true

**Comment by sappelhoff** [comment]
awesome :-) what does the check actually do?

**Comment by larsoner** [comment]
IIRC it checks to make sure all characters are in the ASCII range, no UTF-8 allowed

**Pull request merged**
