### PR TITLE
Add Compumedics types and remove sample TMS type

### PR DESCRIPTION
**Pull request by LorenzE**

### CODE REVIEW

**Comment by larsoner** [comment]
Looks good to me.

@jnenonen @mkajola are you okay with these new constants for this system?

**Comment by larsoner** [comment]
(And removing a constant that isn't really used, that I recently added -- sorry about that!)

**Comment by jnenonen** [comment]
Suggestion: 1) can you consider using values 9101 and 9102 for compumedics coil types, 2) reserve the free'ed value 8001 for QuSpin OPM?

**Comment by LorenzE** [comment]
@jnenonen Both suggestions are fine with me. @larsoner If you agree I will change the current PRs (fiff_constants, mne-python, mne-cpp) and recompute the coil_def.dat with @mshamalainen

**Comment by larsoner** [comment]
It looks like the rule of thumb is each manufacturer gets a range starting with 1000. So if Compumedics makes the KRISS sensor (9001) then I agree 9101/9102 are good choices. Otherwise 9101/9102 do not seem to fit the pattern.

**Pull request merged**
